import Header from '@/components/Header/Header'
import './globals.css'
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import CryptoContext from '@/utils/CryptoContext'
import ReactQueryProvider from '@/utils/ReactQueryProvider'

const roboto = Roboto({ weight: ['400', '700'], subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Crypto currency',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			<body className={` bg-gray-900 text-white ${roboto.className}`}>
				<ReactQueryProvider>
					<CryptoContext>
						<div className='container mx-auto px-5 sm:px-0'>
							<Header />
							{children}
						</div>
					</CryptoContext>
				</ReactQueryProvider>
			</body>
		</html>
	)
}
